[project]
name = "ollami"
version = "0.1.0"
description = "Ollami - The AI assistant for your desktop!"
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
    "pyloid>=0.24.8",
    "pyloid-builder>=0.1.1",
]
